[deps]
Changelog = "5217a498-cd5d-4ec6-b8c2-9b85a09b6e3e"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
CurveFit = "5a033b19-8c74-5913-a970-47c3779ef25c"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"

[sources]
CurveFit = {path = ".."}

[compat]
Documenter = "1"
